openapi: 3.0.1
info:
  title: ' api/v4/applications'
  version: v4
  description: Needs description.
  termsOfService: https://about.gitlab.com/terms/
  license:
    name: CC BY-SA 4.0
    url: https://gitlab.com/gitlab-org/gitlab/-/blob/master/LICENSE
servers:
  - url: https://www.gitlab.com/api/
security:
  - ApiKeyAuth: []
tags: []
paths:
  /api/v4/applications/{id}:
    delete:
      tags:
        - Applications
      summary: 'Delete An Application '
      description: Delete a specific application
      operationId: deleteApiV4ApplicationsId
      parameters:
        - name: id
          in: path
          description: The ID of the application (not the application_id)
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: Delete an application
          content: {}
  /api/v4/applications:
    get:
      tags:
        - Applications
      summary: 'Get Applications '
      description: List all registered applications
      operationId: getApiV4Applications
      responses:
        '200':
          description: Get applications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/API_Entities_Application'
    post:
      tags:
        - Applications
      summary: 'Create A New Application '
      description: This feature was introduced in GitLab 10.5
      operationId: postApiV4Applications
      requestBody:
        content:
          application/json:
            schema:
              required:
                - name
                - redirect_uri
                - scopes
              properties:
                name:
                  type: string
                  description: Name of the application.
                redirect_uri:
                  type: string
                  description: Redirect URI of the application.
                scopes:
                  type: string
                  description: >-
                    Scopes of the application. You can specify multiple scopes
                    by separating\
                                                     each scope using a space
                confidential:
                  type: boolean
                  description: >-
                    The application is used where the client secret can be kept
                    confidential. Native mobile apps \
                                            and Single Page Apps are considered non-confidential. Defaults to true if not supplied
                  default: true
        required: true
      responses:
        '200':
          description: Create a new application
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/API_Entities_ApplicationWithSecret'
components:
  schemas:
    API_Entities_ApplicationWithSecret:
      type: object
      properties:
        id:
          type: string
        application_id:
          type: string
          example: 5832fc6e14300a0d962240a8144466eef4ee93ef0d218477e55f11cf12fc3737
        application_name:
          type: string
          example: MyApplication
        callback_url:
          type: string
          example: https://redirect.uri
        confidential:
          type: boolean
          example: true
        secret:
          type: string
          example: ee1dd64b6adc89cf7e2c23099301ccc2c61b441064e9324d963c46902a85ec34
      description: API_Entities_ApplicationWithSecret model
