weekNumber: 28
rule:
  - code: openapi-security-schemes-error
    message: Security Scheme
  - code: openapi-info-contact-info
    message: Contact Object
  - code: openapi-info-contact-name-error
    message: Contact Name
  - code: openapi-info-contact-url-error
    message: Contact URL
  - code: openapi-info-contact-email-info
    message: Contact Email
  - code: openapi-info-description-info
    message: Info Description
  - code: openapi-info-license-info
    message: License Object
  - code: openapi-info-license-name-info
    message: Info License Name
  - code: openapi-info-license-url-info
    message: Info License URL
  - code: openapi-info-terms-of-service-info
    message: Terms of Service
  - code: openapi-info-title-info
    message: Info Title
  - code: openapi-info-title-upper-case-warn
    message: Info Title Upper Case
  - code: openapi-info-version-info
    message: Info Version
  - code: openapi-version-semantic-info
    message: Semantic Versioning
  - code: openapi-openapi-version-301-info
    message: 3.0.1 Version of OpenAPI
  - code: openapi-openapi-version-310-info
    message: 3.1.0 Version of OpenAPI
  - code: openapi-no-api-in-path-error
    message: No API in Path
  - code: openapi-no-api-in-path-info
    message: No API in Path
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
  - code: openapi-path-description-warn
    message: Path Description
  - code: openapi-no-request-body-on-get-info
    message: GET Request Body
  - code: openapi-operations-description-info
    message: Operation Description
  - code: openapi-operations-operation-ids-info
    message: Operation ID.
  - code: openapi-parameters-required-info
    message: Parameter has a required property.
  - code: openapi-parameters-description-info
    message: Parameter Description
  - code: openapi-parameters-query-names-camel-case-error
    message: Parameter Query Name Camel Case
  - code: openapi-parameters-query-names-snake-case-error
    message: Parameter Query Name Snake Case
  - code: openapi-parameters-in-info
    message: Parameters In
  - code: openapi-parameters-name-info
    message: Parameter Name
  - code: openapi-parameters-schema-info
    message: Parameter Schema Type
  - code: openapi-parameters-schema-type-string-maxlength-warn
    message: Parameter Schema Type String MaxLength
  - code: openapi-parameters-schema-type-string-minlength-warn
    message: Parameter Schema Type String MinLength
  - code: openapi-parameters-schema-type-string-pattern-warn
    message: Parameter Schema Type String Pattern
  - code: openapi-parameters-schema-type-info
    message: Parameter Schema Type
  - code: openapi-response-get-404-status-code-warn
    message: 404 Status Code for GET Responses
  - code: openapi-response-get-500-status-code-error
    message: 500 Status Code for GET Responses
  - code: openapi-response-get-200-status-code-info
    message: GET Response Has 200 Status Code
  - code: openapi-responses-examples-error
    message: Schema COULD have an example.
  - code: openapi-response-get-200-content-info
    message: GET Content
  - code: openapi-response-get-200-media-type-info
    message: JSON Media Type GET
  - code: openapi-response-get-200-media-type-schema-info
    message: Schema GET
  - code: openapi-response-get-200-schema-components-warn
    message: GET Response 200 Schema Components
  - code: invalid-ref
    message: '''#/components/schemas/ProjectDataPolicies'' does not exist'
  - code: openapi-response-get-200-schema-ref-info
    message: GET Response 200 Schema Ref
  - code: openapi-response-get-400-status-code-info
    message: 400 Status Code for GET Responses
  - code: openapi-responses-examples-error
    message: Schema COULD have an example.
  - code: invalid-ref
    message: '''#/components/schemas/ErrorCollection'' does not exist'
  - code: openapi-responses-examples-error
    message: Schema COULD have an example.
  - code: openapi-responses-examples-error
    message: Schema COULD have an example.
  - code: openapi-operation-security-definitions-info
    message: Operation Security Definition
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-period-none-info
    message: Operation Summary Period
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-tags-object-info
    message: Tag Object
  - code: openapi-tags-one-error
    message: One Tag
