weekNumber: 28
rule:
  - code: openapi-security-schemes-error
    message: Security Scheme
  - code: openapi-info-contact-info
    message: Contact Object
  - code: openapi-info-contact-name-error
    message: Contact Name
  - code: openapi-info-contact-url-error
    message: Contact URL
  - code: openapi-info-contact-email-info
    message: Contact Email
  - code: openapi-info-description-info
    message: Info Description
  - code: openapi-info-license-info
    message: License Object
  - code: openapi-info-license-name-info
    message: Info License Name
  - code: openapi-info-license-url-info
    message: Info License URL
  - code: openapi-info-terms-of-service-info
    message: Terms of Service
  - code: openapi-info-title-info
    message: Info Title
  - code: openapi-info-title-upper-case-info
    message: Info Title Upper Case
  - code: openapi-info-version-info
    message: Info Version
  - code: openapi-version-semantic-info
    message: Semantic Versioning
  - code: openapi-openapi-version-301-info
    message: 3.0.1 Version of OpenAPI
  - code: openapi-openapi-version-310-info
    message: 3.1.0 Version of OpenAPI
  - code: openapi-no-api-in-path-error
    message: No API in Path
  - code: openapi-no-api-in-path-info
    message: No API in Path
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
  - code: openapi-path-description-warn
    message: Path Description
  - code: openapi-no-request-body-on-get-info
    message: GET Request Body
  - code: openapi-operation-security-definitions-error
    message: Operation Security Definition
  - code: openapi-operations-operation-ids-error
    message: Operation ID.
  - code: openapi-operations-description-info
    message: Operation Description
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-period-none-info
    message: Operation Summary Period
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-operation-security-definitions-error
    message: Operation Security Definition
  - code: openapi-operations-operation-ids-error
    message: Operation ID.
  - code: openapi-request-body-on-put-error-info
    message: Request Body PUT
  - code: openapi-operations-description-info
    message: Operation Description
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-period-none-info
    message: Operation Summary Period
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-tags-object-info
    message: Tag Object
  - code: openapi-tags-one-error
    message: One Tag
