weekNumber: 28
rule:
  - code: openapi-security-schemes-error
    message: Security Scheme
  - code: openapi-info-contact-info
    message: Contact Object
  - code: openapi-info-contact-name-error
    message: Contact Name
  - code: openapi-info-contact-url-error
    message: Contact URL
  - code: openapi-info-contact-email-info
    message: Contact Email
  - code: openapi-info-description-info
    message: Info Description
  - code: openapi-info-license-info
    message: License Object
  - code: openapi-info-license-name-info
    message: Info License Name
  - code: openapi-info-license-url-info
    message: Info License URL
  - code: openapi-info-terms-of-service-info
    message: Terms of Service
  - code: openapi-info-title-info
    message: Info Title
  - code: openapi-info-title-upper-case-warn
    message: Info Title Upper Case
  - code: openapi-info-version-info
    message: Info Version
  - code: openapi-version-semantic-info
    message: Semantic Versioning
  - code: openapi-openapi-version-301-info
    message: 3.0.1 Version of OpenAPI
  - code: openapi-openapi-version-310-info
    message: 3.1.0 Version of OpenAPI
  - code: openapi-no-api-in-path-error
    message: No API in Path
  - code: openapi-no-api-in-path-info
    message: No API in Path
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
  - code: openapi-path-description-warn
    message: Path Description
  - code: openapi-operations-description-info
    message: Operation Description
  - code: openapi-operations-description-length-error
    message: Operation Description Length
  - code: openapi-operations-operation-ids-info
    message: Operation ID.
  - code: openapi-request-body-on-post-info
    message: Request Body POST
  - code: openapi-request-body-content-on-post-info
    message: Request Body Content POST
  - code: openapi-request-body-have-content-info
    message: Request Body Content
  - code: openapi-request-body-have-application-json-info
    message: Request Body Application JSON
  - code: openapi-request-body-json-media-type-on-post-info
    message: JSON Media Type POST
  - code: openapi-request-body-have-schema-info
    message: Request Body Schema
  - code: invalid-ref
    message: '''#/components/schemas/BulkPermissionsRequestBean'' does not exist'
  - code: openapi-request-body-schema-ref-info
    message: Request Body Schema Ref
  - code: openapi-response-post-201-status-code-error
    message: POST 201 Status Code
  - code: openapi-response-post-404-status-code-warn
    message: 404 Status Code for POST Responses
  - code: openapi-response-post-500-status-code-error
    message: 500 Status Code for POST Responses
  - code: invalid-ref
    message: '''#/components/schemas/BulkPermissionGrants'' does not exist'
  - code: openapi-response-post-400-status-code-info
    message: 400 Status Code for POST Responses
  - code: invalid-ref
    message: '''#/components/schemas/ErrorCollection'' does not exist'
  - code: openapi-operation-security-definitions-info
    message: Operation Security Definition
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-period-none-info
    message: Operation Summary Period
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-no-api-in-path-error
    message: No API in Path
  - code: openapi-no-api-in-path-info
    message: No API in Path
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
  - code: openapi-path-description-warn
    message: Path Description
  - code: openapi-operations-description-info
    message: Operation Description
  - code: openapi-operations-operation-ids-info
    message: Operation ID.
  - code: openapi-request-body-on-post-info
    message: Request Body POST
  - code: openapi-request-body-content-on-post-info
    message: Request Body Content POST
  - code: openapi-request-body-have-content-info
    message: Request Body Content
  - code: openapi-request-body-have-application-json-info
    message: Request Body Application JSON
  - code: openapi-request-body-json-media-type-on-post-info
    message: JSON Media Type POST
  - code: openapi-request-body-have-schema-info
    message: Request Body Schema
  - code: invalid-ref
    message: '''#/components/schemas/PermissionsKeysBean'' does not exist'
  - code: openapi-request-body-schema-ref-info
    message: Request Body Schema Ref
  - code: openapi-response-post-201-status-code-error
    message: POST 201 Status Code
  - code: openapi-response-post-404-status-code-warn
    message: 404 Status Code for POST Responses
  - code: openapi-response-post-500-status-code-error
    message: 500 Status Code for POST Responses
  - code: invalid-ref
    message: '''#/components/schemas/PermittedProjects'' does not exist'
  - code: openapi-response-post-400-status-code-info
    message: 400 Status Code for POST Responses
  - code: openapi-operation-security-definitions-info
    message: Operation Security Definition
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-period-none-info
    message: Operation Summary Period
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-tags-object-info
    message: Tag Object
  - code: openapi-tags-one-error
    message: One Tag
